import Head from "next/head";
import { useSelector, useDispatch } from "react-redux";
import { RootState } from "../../redux/store";
import Button from "../../components/Button/Button";
import styles from "../../styles/GameOver.module.scss";

const buttons = [
  {
    name: "confirm",
    link: "game",
  },
  {
    name: "skip",
    link: "/",
  },
];

export default function GameOver() {
  const score = useSelector((state: RootState) => state.counter.score);
  const dispatch = useDispatch();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.scoreWrapper}>
        <h2 className={styles.score}>{score} Points</h2>
        <input
          className={styles.userNameInput}
          type="text"
          placeholder="Your name..."
        />
        {buttons.map((button) => (
          <Button key={button.name} name={button.name} link={button.link} />
        ))}
      </div>
    </>
  );
}
