import Head from "next/head";
import { useSelector, useDispatch } from "react-redux";

import AnswerButton from "../../components/AnswerButton/AnswerButton";
import { RootState } from "../../redux/store";
import { increment, reset } from "../../redux/score";
import { addHighScore } from "../../redux/highscores";

export default function GamePage() {
  const score = useSelector((state: RootState) => state.counter.score);
  const dispatch = useDispatch();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>score {score}</p>
      <AnswerButton name="yes" onClick={() => dispatch(increment())} />
      <AnswerButton
        name="no"
        onClick={() =>
          dispatch(addHighScore({ name: "sdasdsa", score: score }))
        }
      />
    </>
  );
}
