import Head from "next/head";
import { useState } from "react";
import AnswerButton from "../../components/AnswerButton/AnswerButton";

export default function GamePage() {
  const [score, setScore] = useState(0);

  function addPoint() {
    setScore((prevScore) => prevScore + 1);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>game page</p>
      <AnswerButton name="yes" onClick={addPoint} />
      <AnswerButton name="no" />
    </>
  );
}
