import Head from "next/head";
import Button from "../../components/Button/Button";

import styles from "../../styles/About.module.scss";

export default function AboutPage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.aboutWrapper}>
        <p className={styles.aboutDescription}>
          Welcome to the best show on earth! <br />
          This is the game based on a podcast show from the Big Bang Theory TV
          series. You will learn a lot about flags and countries. Play with your
          friends and enjoy the game!
        </p>

        <Button name="back" link="/" />
      </div>
    </>
  );
}
