import Head from "next/head";
import styles from "../styles/Home.module.css";
import Button from "../components/Button/Button";
import { useEffect, useState } from "react";

const buttons = [
  {
    name: "play",
    link: "game",
  },
  {
    name: "learn",
    link: "flagpedia",
  },
  {
    name: "whaaaat",
    link: "about",
  },
];

export default function Home() {
  const [countries, setCountries] = useState([]);

  async function fetchCountries() {
    const response = await fetch("https://restcountries.com/v3.1/all");
    const data = await response.json();
    setCountries(data);
  }

  useEffect(() => {
    fetchCountries();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.buttonsWrapper}>
        {buttons.map((button) => (
          <Button key={button.name} name={button.name} link={button.link} />
        ))}
      </div>
    </>
  );
}
